name: pyinstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: jcwillox/install-tool-action@v1
      with:
        repo: "upx/upx"
        download_url: "/releases/download/v5.0.1/upx-5.0.1-win64.zip"
        bin_path: "upx-5.0.1-win64"

    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: pyinstaller main_gui.spec

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
